/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package church_projet;

import church_projet.Acceuil.acc;
import church_projet.login.login;
import javax.swing.JOptionPane;

/**
 *
 * @author Ibrahim
 */
public class splash extends javax.swing.JFrame {

    private static void DISPOSE_ON_CLOSE(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form splash
     */
    public splash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        write = new javax.swing.JLabel();
        loaginumber = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        texte = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        write.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        write.setText("Loading.....");
        jPanel1.add(write, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        loaginumber.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        loaginumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loaginumber.setText("99");
        jPanel1.add(loaginumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 80, -1));

        loadingbar.setBackground(new java.awt.Color(255, 255, 255));
        loadingbar.setForeground(new java.awt.Color(255, 255, 0));
        loadingbar.setBorder(null);
        jPanel1.add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 310, 640, 20));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_bible3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 360, 170));

        texte.setFont(new java.awt.Font("FrankRuehl", 3, 36)); // NOI18N
        texte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(texte, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        splash Splash = new splash();
        Splash.setVisible(true);
        /* Create and display the form */
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(70);
                Splash.loaginumber.setText(i + "%");
                //Splash.loadingbar.setValue(i);
                if (i == 10) {
                    Splash.write.setText("runing on Modules...");
                }
                if (i == 10) {
                    Splash.write.setText("Loading Modules...");
                }
                if (i == 50) {
                    Splash.write.setText("Connecting to Database...");
                }
                if (i == 70) {
                    Splash.write.setText("Connction Succeful !");
                }
                if (i == 80) {
                    Splash.write.setText("Lanching Application...");
                    Splash.texte.setText("Welcome");
                }
                if (i == 100) {
                    login login = new login();
                    login.setVisible(true);
                    
                }
                Splash.loadingbar.setValue(i);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel loaginumber;
    private javax.swing.JLabel texte;
    private javax.swing.JLabel write;
    // End of variables declaration//GEN-END:variables
}
